<a href="https://colab.research.google.com/github/Milindkr/EDA_Projects/blob/main/movies_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone "https://github.com/HarshvardhanSingh-13/Datasets"

fatal: destination path 'Datasets' already exists and is not an empty directory.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Datasets/IMDB Movies/movies.csv")

In [ ]:
df.head()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175 min,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87 min,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127 min,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100 min,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
4,tt10809742,Collision,2022,3.8,TV-MA,99 min,"Crime, Drama, Thriller",656,"134,966,411",nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.

In [ ]:
df.tail()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
19803,tt0459423,Kahaani Gudiya Ki...: True Story of a Woman,2008,6.2,Not Rated,112 min,"Biography, Drama",41,"44,435",nm1909606,Prabhakar Shukla,"nm0244890,nm0952232,nm1056425,nm6389513","Divya Dutta,Arif Zakaria,Rajpal Naurang Yadav,...","A tragic saga about a woman named Gudiya, whos..."
19804,tt0119621,Mark Twain's America in,1998,6.5,G,52 min,"Documentary, Biography",48,"2,281,741",nm0522844,Stephen Low,"nm0000843,nm0640297,nm4700843,nm1838044","Anne Bancroft,Dennis O'Connor,Kim Parr,LeeAnn ...",Interweaves Twain's life and times with the li...
19805,tt0168950,Let It Come Down: The Life of Paul Bowles,1998,6.9,Not Rated,75 min,"Documentary, Biography",125,"9,188",nm0047028,Jennifer Baichwal,"nm0101247,nm0123221,nm0155822,nm0159383","Paul Bowles,William S. Burroughs,Cherifa,Moham...",Add a Plot
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92 min,"Documentary, Biography",146,"159,403","/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...
19807,tt0116481,Hands on a Hardbody: The Documentary,1997,7.6,PG,98 min,"Documentary, Comedy, Drama",2167,"492,876",nm0082835,S.R. Bindler,"nm0021057,nm1828145,nm0185044,nm0190040","Sid Allen,Brent Baskin,Greg Cox,J.C. Crum",Twenty-four contestants compete in an enduranc...

In [ ]:
df.sample()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
1094,tt0242445,Exit Wounds,2001,5.6,R,101 min,"Action, Crime, Thriller",35289,"51,758,599",nm0005647,Andrzej Bartkowiak,"nm0000219,nm0229422,nm0913460,nm0026364","Steven Seagal,DMX,Isaiah Washington,Anthony An...","Orin Boyd, a tough cop in an inner-city precin..."

In [ ]:
df.sample(5)

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
8788,tt0075143,Al-risâlah,1976,8.9,PG,207 min,"Biography, Drama, History","9,160","164,906",nm0002160,Moustapha Akkad,"nm1772638,nm0913307,nm0312072,nm0850193","Abdallah Gheith,Mona Wassef,Hamdy Gheith,Ali A...","The story of prophet ""Muhammad"" and the delive..."
17930,tt3141912,Gun Woman,2014,4.8,Not Rated,86 min,"Action, Thriller","3,229","579,055",nm1562288,Kurando Mitsutake,"nm3051038,nm3468871,nm0800482,nm0436456","Jennifer Mullaney,Matthew Floyd Miller,Dean Si...",A brilliant doctor on a quest for revenge buys...
17926,tt0435696,The Russian Specialist,2005,5.5,R,94 min,"Action, Drama, Thriller","3,839","641,886",nm0000185,Dolph Lundgren,"nm0000185,nm0002027,nm0678419,nm1483637","Dolph Lundgren,Ben Cross,Ivan Petrushinov,Oliv...",A Russian ex-Spetsnaz working as a mechanic in...
1055,tt0072732,Brannigan,1975,6.1,PG,111 min,"Action, Comedy, Crime","5,718","10,387,706",nm0382779,Douglas Hickox,"nm0000078,nm0000277,nm0002096,nm0002072","John Wayne,Richard Attenborough,Judy Geeson,Me...",Chicago Police Lieutenant Jim Brannigan is sen...
11759,tt0061636,Face to Face,1967,7.2,R,111 min,Western,"3,016","2,600,000",nm0813177,Sergio Sollima,"nm0002231,nm0587401,nm0074125,nm0595297","Gian Maria Volontè,Tomas Milian,William Berger...",A history professor has a chance meeting with ...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  object
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.1+ MB

- In the above "duration" Column it written as object but it should be in integers
- "votes"
- "gross_income"

In [ ]:
df.describe()

               year        rating
count  19808.000000  19808.000000
mean    1995.546597      6.041973
std       22.801725      1.206831
min     1894.000000      1.100000
25%     1983.000000      5.300000
50%     2003.000000      6.200000
75%     2014.000000      6.900000
max     2022.000000      9.700000

In [ ]:
df.isnull()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19803,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19804,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19805,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19806,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19807,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

id                0
name              0
year              0
rating            0
certificate       0
duration          0
genre             0
votes             0
gross_income      0
directors_id      0
directors_name    0
stars_id          0
stars_name        0
description       0
dtype: int64

What if I want to see rating column

In [ ]:
df["rating"]

0        9.2
1        7.3
2        6.3
3        6.9
4        3.8
        ...
19803    6.2
19804    6.5
19805    6.9
19806    7.4
19807    7.6
Name: rating, Length: 19808, dtype: float64

What if I want to see average/mean of the rating

In [ ]:
df["rating"].mean()

np.float64(6.041972940226171)

What is I want to see median and mode

In [ ]:
df['rating'].median()

6.2

In [ ]:
df["rating"].mode()

0    6.4
Name: rating, dtype: float64

In [ ]:
# rating > 4

df["rating"] > 4  #You see It shows boolean value but we want data

0         True
1         True
2         True
3         True
4        False
         ...
19803     True
19804     True
19805     True
19806     True
19807     True
Name: rating, Length: 19808, dtype: bool

In [ ]:
#  df["rating"] > 4  -You see It shows boolean value but we want data then what we do

df[df["rating"] > 4]  # -- Now we get the data

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175 min,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87 min,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127 min,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100 min,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
5,tt0071562,The Godfather Part II,1974,9.0,R,202 min,"Crime, Drama",1239038,"57,300,000",nm0000338,Francis Ford Coppola,"nm0000199,nm0000134,nm0000380,nm0000473","Al Pacino,Robert De Niro,Robert Duvall,Diane K...",The early life and career of Vito Corleone in ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19803,tt0459423,Kahaani Gudiya Ki...: True Story of a Woman,2008,6.2,Not Rated,112 min,"Biography, Drama",41,"44,435",nm1909606,Prabhakar Shukla,"nm0244890,nm0952232,nm1056425,nm6389513","Divya Dutta,Arif Zakaria,Rajpal Naurang Yadav,...","A tragic saga about a woman named Gudiya, whos..."
19804,tt0119621,Mark Twain's America in,1998,6.5,G,52 min,"Documentary, Biography",48,"2,281,741",nm0522844,Stephen Low,"nm0000843,nm0640297,nm4700843,nm1838044","Anne Bancroft,Dennis O'Connor,Kim Parr,LeeAnn ...",Interweaves Twain's life and times with the li...
19805,tt0168950,Let It Come Down: The Life of Paul Bowles,1998,6.9,Not Rated,75 min,"Documentary, Biography",125,"9,188",nm0047028,Jennifer Baichwal,"nm0101247,nm0123221,nm0155822,nm0159383","Paul Bowles,William S. Burroughs,Cherifa,Moham...",Add a Plot
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92 min,"Documentary, Biography",146,"159,403","/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...
19807,tt0116481,Hands on a Hardbody: The Documentary,1997,7.6,PG,98 min,"Documentary, Comedy, Drama",2167,"492,876",nm0082835,S.R. Bindler,"nm0021057,nm1828145,nm0185044,nm0190040","Sid Allen,Brent Baskin,Greg Cox,J.C. Crum",Twenty-four contestants compete in an enduranc...

In [ ]:
df["rating"].min()

1.1

In [ ]:
df["rating"].max()

9.7

In [ ]:
df["rating"].astype(int)

0        9
1        7
2        6
3        6
4        3
        ..
19803    6
19804    6
19805    6
19806    7
19807    7
Name: rating, Length: 19808, dtype: int64

# Cleaning Part

### I have to clean

- "duration"
- "votes"
- "gross_income"

## Work on duration Column

In [ ]:
df["duration"]

0        175 min
1         87 min
2        127 min
3        100 min
4         99 min
          ...
19803    112 min
19804     52 min
19805     75 min
19806     92 min
19807     98 min
Name: duration, Length: 19808, dtype: object

In [ ]:
df["duration"].astype(int)

ValueError: invalid literal for int() with base 10: '175 min'

In [ ]:
# Now what to do is first convort it into string(str) then do operations of string like split()



# Step - 1



df["duration"].str.split()

0        [175, min]
1         [87, min]
2        [127, min]
3        [100, min]
4         [99, min]
            ...
19803    [112, min]
19804     [52, min]
19805     [75, min]
19806     [92, min]
19807     [98, min]
Name: duration, Length: 19808, dtype: object

In [ ]:
# Step - 2

df["duration"].str.replace("min","")

# Now it actually not replacing on the main column so for replacing this what do is

0        175
1         87
2        127
3        100
4         99
         ...
19803    112
19804     52
19805     75
19806     92
19807     98
Name: duration, Length: 19808, dtype: object

In [ ]:
# Step -3

df["duration"] = df["duration"].str.replace("min","")

In [ ]:
# Step - 4

df["duration"] = df["duration"].str.replace(",","")

In [ ]:
df["duration"]

0        175
1         87
2        127
3        100
4         99
         ...
19803    112
19804     52
19805     75
19806     92
19807     98
Name: duration, Length: 19808, dtype: object

In [ ]:
df["duration"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 19808 entries, 0 to 19807
Series name: duration
Non-Null Count  Dtype
--------------  -----
19808 non-null  object
dtypes: object(1)
memory usage: 154.9+ KB

In [ ]:
# Now we want to chnage the dataType of this

# Step - 5

df["duration"].astype(int)

0        175
1         87
2        127
3        100
4         99
        ...
19803    112
19804     52
19805     75
19806     92
19807     98
Name: duration, Length: 19808, dtype: int64

In [ ]:
# For Parmanetally chnage

# Step - 6

df["duration"] = df["duration"].astype(int)

In [ ]:
# Show

df["duration"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 19808 entries, 0 to 19807
Series name: duration
Non-Null Count  Dtype
--------------  -----
19808 non-null  int64
dtypes: int64(1)
memory usage: 154.9 KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  int64
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 2.1+ MB

## Work on Votes Column

In [ ]:
df.head()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
4,tt10809742,Collision,2022,3.8,TV-MA,99,"Crime, Drama, Thriller",656,"134,966,411",nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  int64
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 2.1+ MB

In [ ]:
df["votes"] = df["votes"].str.replace(",","")

In [ ]:
df["votes"] = df["votes"].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  int64
 6   genre           19808 non-null  object
 7   votes           19808 non-null  int64
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(3), object(10)
memory usage: 2.1+ MB